In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
import warnings

warnings.filterwarnings("ignore")
warnings.filterwarnings("ignore", category=DeprecationWarning)

In [2]:
data = pd.read_csv("Telugu_Char_Gabor_.csv")
data

,ImageName,Label,Theta0_Lambda1_LocalEnergy,Theta0_Lambda1_MeanAmplitude,Theta0_Lambda0_LocalEnergy,Theta0_Lambda0_MeanAmplitude,Theta0_Lambda0_LocalEnergy.1,Theta0_Lambda0_MeanAmplitude.1,Theta0_Lambda0_LocalEnergy.2,Theta0_Lambda0_MeanAmplitude.2,...,Theta0_Lambda1_LocalEnergy.3,Theta0_Lambda1_MeanAmplitude.3,Theta0_Lambda0_LocalEnergy.12,Theta0_Lambda0_MeanAmplitude.12,Theta0_Lambda0_LocalEnergy.13,Theta0_Lambda0_MeanAmplitude.13,Theta0_Lambda0_LocalEnergy.14,Theta0_Lambda0_MeanAmplitude.14,Theta0_Lambda0_LocalEnergy.15,Theta0_Lambda0_MeanAmplitude.15
0,290.jpg,bha,20156,17075,16619,15520,19773,20156,17075,16619,...,1858906,1852842,1842127,1040502,1098244,1857951,1851467,1841849,1041069,1098799
1,279.jpg,bha,19326,15768,17330,17396,21259,19326,15768,17330,...,1866522,1860394,1848869,1044376,1102343,1865684,1859364,1848831,1044848,1102800
2,298.jpg,bha,20938,16923,16760,15988,18057,20938,16923,16760,...,1861372,1856232,1845456,1042043,1099911,1860029,1854961,1845479,1042506,1100367
3,281.jpg,bha,19734,16267,18519,16972,20269,19734,16267,18519,...,1868238,1861985,1849059,1044074,1102055,1866511,1859902,1848786,1044744,1102702
4,387.jpg,bha,21734,16535,18278,16804,22514,21734,16535,18278,...,1863126,1855977,1844264,1042438,1100163,1860754,1853576,1843932,1043261,1100975
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5513,y (19).jpg,ye,18502,17326,18126,18901,19733,18502,17326,18126,...,1873048,1866662,1853211,1045718,1103818,1870341,1863212,1852196,1046725,1104791
5514,y (14).jpg,ye,18672,15327,16320,16528,18966,18672,15327,16320,...,1867402,1862358,1852193,1045734,1103826,1865820,1860328,1851856,1046317,1104381
5515,y (17).jpg,ye,16459,17683,19206,16945,16914,16459,17683,19206,...,1877034,1871957,1860389,1050036,1108391,1874900,1868459,1859471,1051224,1109559
5516,y (22).jpg,ye,18736,14454,17102,15342,18828,18736,14454,17102,...,1871030,1865540,1854703,1047235,1105375,1867776,1861787,1853745,1048529,1106641
5517,y (9).jpg,ye,17163,15997,16898,16774,18212,17163,15997,16898,...,1870722,1865383,1855707,1048153,1106347,1869272,1863952,1855416,1048485,1106664

# **A1**

In [3]:
# Identifying non-numeric columns
non_numeric_columns = data.select_dtypes(exclude=['number']).columns.tolist()

# Removing non-numeric columns
numeric_data = data.drop(non_numeric_columns, axis=1)

# Preprocessing the numeric data (scaling or normalization might be needed)
scaler = StandardScaler()
data_scaled = scaler.fit_transform(numeric_data)

# K-means clustering with k = 3
kmeans3 = KMeans(n_clusters=3)
kmeans3.fit(data_scaled)

# K-means clustering with k = 5
kmeans5 = KMeans(n_clusters=5)
kmeans5.fit(data_scaled)

# Checking inertia or silhouette scores for evaluating the clustering
print("K=3 Inertia:", kmeans3.inertia_)
print("K=5 Inertia:", kmeans5.inertia_)

K=3 Inertia: 78499.0691731619
K=5 Inertia: 53353.88512542014

# **A2**

In [ ]:
# Determining the ideal k value using the Elbow Method
distortions = []
K = range(1, 31)
for k in K:
    kmeans = KMeans(n_clusters=k)
    kmeans.fit(data_scaled)
    distortions.append(kmeans.inertia_)

# Plotting the Elbow graph
plt.figure(figsize=(8, 6))
plt.plot(K, distortions, 'bx-')
plt.xlabel('k')
plt.ylabel('Average Distortion')
plt.title('Elbow Method For Optimal k')
plt.show()

# **A3**

In [ ]:
import scipy.cluster.hierarchy as sch

# Hierarchical clustering using Agglomerative Clustering
plt.figure(figsize=(30, 7))
dendrogram = sch.dendrogram(sch.linkage(data_scaled, method='ward'))
plt.title('Dendrogram')
plt.xlabel('Samples')
plt.ylabel('Distance')
plt.show()

# **A4**

In [7]:
data

,ImageName,Label,Theta0_Lambda1_LocalEnergy,Theta0_Lambda1_MeanAmplitude,Theta0_Lambda0_LocalEnergy,Theta0_Lambda0_MeanAmplitude,Theta0_Lambda0_LocalEnergy.1,Theta0_Lambda0_MeanAmplitude.1,Theta0_Lambda0_LocalEnergy.2,Theta0_Lambda0_MeanAmplitude.2,...,Theta0_Lambda1_LocalEnergy.3,Theta0_Lambda1_MeanAmplitude.3,Theta0_Lambda0_LocalEnergy.12,Theta0_Lambda0_MeanAmplitude.12,Theta0_Lambda0_LocalEnergy.13,Theta0_Lambda0_MeanAmplitude.13,Theta0_Lambda0_LocalEnergy.14,Theta0_Lambda0_MeanAmplitude.14,Theta0_Lambda0_LocalEnergy.15,Theta0_Lambda0_MeanAmplitude.15
0,290.jpg,bha,20156,17075,16619,15520,19773,20156,17075,16619,...,1858906,1852842,1842127,1040502,1098244,1857951,1851467,1841849,1041069,1098799
1,279.jpg,bha,19326,15768,17330,17396,21259,19326,15768,17330,...,1866522,1860394,1848869,1044376,1102343,1865684,1859364,1848831,1044848,1102800
2,298.jpg,bha,20938,16923,16760,15988,18057,20938,16923,16760,...,1861372,1856232,1845456,1042043,1099911,1860029,1854961,1845479,1042506,1100367
3,281.jpg,bha,19734,16267,18519,16972,20269,19734,16267,18519,...,1868238,1861985,1849059,1044074,1102055,1866511,1859902,1848786,1044744,1102702
4,387.jpg,bha,21734,16535,18278,16804,22514,21734,16535,18278,...,1863126,1855977,1844264,1042438,1100163,1860754,1853576,1843932,1043261,1100975
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5513,y (19).jpg,ye,18502,17326,18126,18901,19733,18502,17326,18126,...,1873048,1866662,1853211,1045718,1103818,1870341,1863212,1852196,1046725,1104791
5514,y (14).jpg,ye,18672,15327,16320,16528,18966,18672,15327,16320,...,1867402,1862358,1852193,1045734,1103826,1865820,1860328,1851856,1046317,1104381
5515,y (17).jpg,ye,16459,17683,19206,16945,16914,16459,17683,19206,...,1877034,1871957,1860389,1050036,1108391,1874900,1868459,1859471,1051224,1109559
5516,y (22).jpg,ye,18736,14454,17102,15342,18828,18736,14454,17102,...,1871030,1865540,1854703,1047235,1105375,1867776,1861787,1853745,1048529,1106641
5517,y (9).jpg,ye,17163,15997,16898,16774,18212,17163,15997,16898,...,1870722,1865383,1855707,1048153,1106347,1869272,1863952,1855416,1048485,1106664

In [ ]:
from sklearn.feature_selection import SequentialFeatureSelector
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
# Separating features and target

X = data.drop(columns=['Label','ImageName'])  # Features
y = data['Label']  # Target

# Selecting only numeric columns for feature selection
numeric_columns = X.select_dtypes(include=['number']).columns.tolist()
X_numeric = X[numeric_columns]